import { createContext, useContext, useEffect, useState } from 'react';

const LANGUAGE_STORAGE_KEY = 'app-language';

const translations = {
  en: {
    language: {
      english: 'English',
      somali: 'Somali',
      englishShort: 'ENG',
      somaliShort: 'SOM',
      selectLanguage: 'Language',
      deepTranslate: 'Instant English / Somali',
    },
    nav: {
      home: 'Home',
      aboutUs: 'About Us',
      menu: 'Menu',
      orderOnline: 'Order Online',
      reservations: 'Reservations',
      contact: 'Contact',
    },
    brand: {
      name: 'Sowda restaurant',
      subtitle: 'Premium Gourmet Dining',
    },
    userMenu: {
      adminDashboard: 'Admin Dashboard',
      myProfileOrders: 'My Profile & Orders',
      logout: 'Logout',
      login: 'Login',
      userLogin: 'User Login',
      adminLogin: 'Admin Login',
      register: 'Register',
      continueShopping: 'Continue Shopping',
      remove: 'Remove',
      settings: 'Settings',
    },
    footer: {
      navigation: 'Navigation',
      openingHours: 'Opening Hours',
      contactUs: 'Contact Us',
      allRights: 'All rights reserved. Designed with elegance.',
      ourMenu: 'Our Menu',
    },
    buttons: {
      bookTable: 'Book A Table',
      orderOnline: 'Order Online',
      viewFullMenu: 'View Full Menu',
      sendMessage: 'Send Message',
      proceedToCheckout: 'Proceed to Checkout',
      exploreMenu: 'Explore Our Menu',
      placeFirstOrder: 'Place Your First Order',
      registerAccount: 'Register Account',
      loginSession: 'Login Session',
      backToHome: 'Back to Home',
      reserveNow: 'Reserve Table Now',
      sendAnotherMessage: 'Send Another Message',
      bookAnotherTable: 'Book Another Table',
      continueShopping: 'Continue Shopping',
      trackOrder: 'Track My Order',
    },
    home: {
      heroBadge: 'Exquisite Fine Dining Experience',
      heroTitle: 'Where Gastronomy Meets Luxury',
      heroDescription: 'Welcome to Sowda restaurant. Immerse your senses in a luxurious culinary journey designed by award-winning French masters.',
      heroImageAlt: 'Restaurant Dining Area',
      heroCaption: 'Sowda restaurant Main Salon',
      michelinText: '3 Michelin',
      organicText: '100% Organic',
      features: [
        {
          title: 'Michelin Starred Chefs',
          description: 'Our kitchen is led by award-winning culinary masters crafting French-inspired gastronomy.',
        },
        {
          title: 'Fresh Organic Ingredients',
          description: 'Every single dish is prepared daily using locally sourced organic produce and premium meats.',
        },
        {
          title: 'Exquisite Atmosphere',
          description: 'Enjoy fine dining with bespoke acoustic designs, luxury lighting, and attentive service.',
        },
      ],
      testimonials: [
        {
          name: 'Sophia Loren',
          role: 'Gourmet Critic',
          rating: 5,
          comment: 'The Lobster Bisque here is a masterpiece. The richness and silky finish are unmatched.',
        },
        {
          name: 'Marcus Aurelius',
          role: 'Regular Guest',
          rating: 5,
          comment: 'Sowda restaurant never ceases to amaze. The Wagyu steak melted like butter, and the service was flawless.',
        },
        {
          name: 'Elena Rostova',
          role: 'Food Blogger',
          rating: 4.5,
          comment: 'Stunning design, gorgeous glassmorphism details, and highly flavorful food.',
        },
      ],
      featuredTitle: 'Featured Creations',
      experienceTitle: 'Elevating Food To An Art Form',
      experienceDescription: 'Our philosophy focuses on purity of flavor, precise execution, and a sensory journey that takes you across classic French regions.',
      reviewTag: 'Reviews',
      reviewHeading: 'What Culinary Enthusiasts Say',
      ctaReserve: 'Reserve Table Now',
      chefSelection: "Chef's Selection",
      diningExperience: 'The Dining Experience',
      starsExcellence: 'Stars Excellence',
      farmToTable: 'Farm-To-Table Sourcing',
    },
    about: {
      storyTag: 'Our Story',
      heading: 'Sowda restaurant',
      intro: 'Founded in 2012, Sowda restaurant represents the culmination of French culinary tradition merged with modern culinary science.',
      chefImageAlt: 'Chef Preparing Food',
      heritageTag: 'Heritage',
      heritageTitle: 'Born From Culinary Passion',
      heritageDescription1: 'Chef Antoine Laurent started the restaurant with a simple goal: to make gourmet dining approachable yet premium.',
      heritageDescription2: 'Located in the heart of the historic district, Sowda restaurant blends classical architecture with warm, modern luxury.',
      metrics: [
        { title: 'Authentic Techniques', description: 'Slow-reduction stocks, hand-kneaded dough, and copper pan searing.' },
        { title: 'Innovation', description: 'State-of-the-art sous-vide control and culinary smoke infusion.' },
        { title: '100% Care', description: 'Local organic sourcing and allergy-friendly attention.' },
      ],
      teamTag: 'The Artisans',
      teamTitle: 'Meet Our Culinary Team',
      team: [
        {
          name: 'Chef Antoine Laurent',
          role: 'Executive Chef & Founder',
          description: 'Trained in Paris under Michelin masters, Antoine has spent 20 years perfecting his craft.',
        },
        {
          name: 'Elena Rostova',
          role: 'Master Pastry Chef',
          description: 'Elena creates artistic desserts combining classical baking with modern style.',
        },
        {
          name: 'Jean-Pierre Dubois',
          role: 'Head Sommelier',
          description: 'Curator of our wine vault, ensuring perfect pairings for every guest.',
        },
      ],
    },
    contact: {
      headerTag: 'Contact Us',
      heading: "We'd Love to Hear From You",
      description: 'Have a question about our menu, private events, or catering? Send us a message and our host team will respond within 24 hours.',
      infoTitle: 'Contact Information',
      hoursTitle: 'Dining Room Hours',
      locationLabel: 'Our Location',
      hotlineLabel: 'Hotline',
      emailLabel: 'Email Address',
      formHeading: 'Send Us A Message',
      successHeading: 'Message Sent!',
      successDescription: 'Thank you for contacting us. Your message has been submitted successfully. Our customer support manager will get back to you shortly.',
      fields: {
        name: 'Your Name',
        email: 'Email Address',
        subject: 'Subject',
        message: 'Message',
      },
      placeholders: {
        name: 'John Doe',
        email: 'john@example.com',
        subject: 'Private Booking Inquiry',
        message: 'Write details of your query...',
      },
      mapLocation: '42 Champs-Élysées',
      mapCity: 'Paris, France 75008',
      mapHint: 'Interactive Map View Simulation',
      hours: [
        { label: 'Monday - Friday', value: '17:00 - 23:00' },
        { label: 'Saturday', value: '12:00 - 23:30' },
        { label: 'Sunday', value: '12:00 - 22:00' },
      ],
      privateEventsTitle: 'Private Events & Banquets',
      privateEventsDescription: 'We host bespoke private dinners, corporate receptions, and wedding banquets for up to 80 guests.',
      privateEventsContact: 'Contact our events manager directly for tailored menus.',
    },
    menu: {
      smallTitle: 'Le Menu',
      heading: 'Experience Our Menu',
      placeholder: 'Search gourmet dishes...',
      defaultSorting: 'Default Sorting',
      priceLow: 'Price: Low to High',
      priceHigh: 'Price: High to Low',
      nameSort: 'Name: A to Z',
      allItems: 'All Items',
      noResultsTitle: 'No Dishes Found',
      noResultsDescription: 'Try modifying your search or changing the filter category.',
    },
    ordering: {
      smallTitle: 'Gourmet Delivery',
      heading: 'Order Online',
      placeholder: 'Search dishes to add to your bag...',
      allItems: 'All Items',
      noItems: 'No items match your selections.',
      bagTitle: 'Your Dining Bag',
      emptyTitle: 'Your bag is empty.',
      emptySubtitle: 'Add delicious gourmet meals from the left list to begin.',
      totalAmount: 'Total Amount',
      freeDelivery: 'Free',
      deliveryFee: 'Delivery Fee',
      checkoutButton: 'Proceed to Checkout',
    },
    cart: {
      headerTag: 'Your Selections',
      heading: 'Shopping Cart',
      orderSummary: 'Order Summary',
      dishDetailsHeader: 'Dish Details',
      priceHeader: 'Price',
      quantityHeader: 'Quantity',
      totalHeader: 'Total',
      priceLabel: 'Price:',
      qtyLabel: 'Qty:',
      totalLabel: 'Total:',
      gourmetSubtotal: 'Gourmet Subtotal',
      estimatedTax: 'Estimated VAT (10%)',
      deliveryFee: 'Delivery / Service Fee',
      complimentary: 'Complimentary',
      totalCost: 'Total cost',
      emptyTitle: 'Your Cart is Empty',
      emptyDescription: 'It looks like you have not added any gourmet dishes to your cart yet. Visit our menu and explore culinary masterpieces.',
    },
    foodDetails: {
      back: 'Back',
      dishNotFoundTitle: 'Dish Not Found',
      dishNotFoundBody: 'The item you are looking for does not exist or has been removed.',
      backToMenu: 'Back to Menu',
      keyIngredients: 'Key Ingredients',
      nutritionInfo: 'Nutrition Info',
      addToCart: 'Add to Cart',
      addedToCart: 'Added to Cart!',
      outOfStock: 'Out of Stock',
      ingredients: [
        'Organic local produce',
        'House-made specialty reductions',
        'Traditional herbs & butter infusion',
        'Hand-selected spices',
      ],
      nutritionLabels: {
        calories: 'Calories',
        protein: 'Protein',
        fat: 'Fat',
        carbs: 'Carbs',
      },
    },
    checkout: {
      headerTag: 'Finalize Dining',
      heading: 'Secure Checkout',
      deliveryDetails: '1. Delivery Details',
      recipientName: 'Recipient Name',
      phoneNumber: 'Phone Number',
      orderType: 'Order Type',
      homeDelivery: 'Home Delivery',
      restaurantPickup: 'Restaurant Pickup',
      deliveryAddress: 'Delivery Address',
      paymentDetails: '2. Settlement Method',
      creditCard: 'Credit/Debit Card',
      cashOnDelivery: 'Cash on Delivery',
      payAtCounter: 'Pay at Counter',
      cardNumber: 'Card Number',
      cardExpiry: 'Expiry Date',
      cardCvc: 'CVC Code',
      confirmOrder: 'Confirm Order',
      authorizingPayment: 'Authorizing Card Payment...',
      orderConfirmed: 'Order Confirmed!',
      orderThankYou: 'Thank you for dining with Sowda restaurant. Your order',
      orderThankYouSuffix: 'has been received and is currently being prepared by our master chefs.',
      orderSummary: 'Order Summary',
      orderStatus: 'Order Status',
      preparationType: 'Preparation Type',
      totalPaid: 'Total Paid',
      modify: 'Modify',
      trackOrder: 'Track My Order',
      backToHome: 'Back to Home',
      subtotal: 'Subtotal',
      vat: 'VAT (10%)',
      grandTotal: 'Grand Total',
    },
    reservations: {
      smallTitle: 'Fine Dining Seating',
      heading: 'Table Reservations',
      description: 'Book your table at Sowda restaurant. Experience exceptional French fine dining and attentive service in our main dining salon or private chambers.',
      guidelinesTitle: 'Reservation Guidelines',
      guidelinesIntro: 'To guarantee a premium atmosphere for all our guests, we maintain basic dining guidelines:',
      policies: [
        { title: 'Dress Code', description: 'Smart elegant. We kindly request guests to avoid athletic wear, beach attire, or casual t-shirts.' },
        { title: 'Punctuality', description: 'Tables are held for a maximum of 15 minutes. Please notify us if you are running late.' },
        { title: 'Cancellation', description: 'Cancellations or changes must be submitted at least 24 hours prior to your slot.' },
      ],
      privateEventsTitle: 'Private Events & Banquets',
      privateEventsDescription: 'We host bespoke private dinners, corporate receptions, and wedding banquets for up to 80 guests. Contact our events manager directly for tailored menus.',
      privateEventsContact: 'Email: events@sowda.com | Tel: +254 724 631727',
    },
    login: {
      heading: 'Customer Login',
      description: 'Sign in to order gourmet meals and manage your bookings.',
      emailLabel: 'Email Address',
      passwordLabel: 'Password',
      emailPlaceholder: 'john@example.com',
      passwordPlaceholder: '••••••••',
      loginButton: 'Login Session',
      registerPrompt: "Don't have an account?",
      registerLink: 'Register Here',
      adminPrompt: 'Are you an admin?',
      adminLink: 'Use the admin login page',
      invalidCredentials: 'Invalid email or password.',
    },
    adminLogin: {
      heading: 'Admin Login',
      description: 'Sign in with your admin credentials to access the Sowda dashboard.',
      adminEmailLabel: 'Admin Email',
      passwordLabel: 'Password',
      emailPlaceholder: 'admin@sowda.com',
      passwordPlaceholder: '••••••••',
      loginButton: 'Admin Login',
      invalidCredentials: 'Invalid admin email or password.',
      needCustomerAccount: 'Need a customer account?',
      userLogin: 'User Login',
      dontHaveAccount: "Don't have an account?",
      registerHere: 'Register Here',
    },
    register: {
      heading: 'Create Account',
      description: 'Sign up to place orders and book reservations instantly.',
      nameLabel: 'Your Name',
      emailLabel: 'Email Address',
      passwordLabel: 'Password',
      confirmPasswordLabel: 'Confirm Password',
      placeholderName: 'John Doe',
      passwordPlaceholder: '••••••••',
      registerButton: 'Register Account',
      existingAccountPrompt: 'Already have an account?',
      loginLink: 'Login Here',
      passwordMismatch: 'Passwords do not match.',
      registrationFailed: 'Registration failed. Please try again.',
    },
    profile: {
      headerTag: 'My Account',
      heading: 'Profile & History',
      ordersTab: 'Orders',
      reservationsTab: 'Bookings',
      settingsTab: 'Settings',
      orderSectionTitle: 'Order',
      orderedOn: 'Ordered on',
      totalPaid: 'Total Paid',
      orderTracker: 'Live Order Tracker',
      cancelledOrder: 'This order was cancelled.',
      noOrders: 'No order history found.',
      placeFirstOrder: 'Place Your First Order',
      noBookings: 'No bookings found.',
      bookATable: 'Book A Table',
      roleLabel: 'Role',
      memberSince: 'Member since',
      settingsTitle: 'Profile Settings',
      nameLabel: 'Your Name',
      emailLabel: 'Email Address',
      newPasswordLabel: 'New Password (optional)',
      updatePasswordPlaceholder: 'Leave blank to keep current password',
      savingChanges: 'Saving changes...',
      profileUpdated: 'Profile updated successfully.',
      updateProfileButton: 'Save Changes',
      profileError: 'Failed to update profile.',
      settingsIntro: 'Update your account information and password below.',
      liveOrderStatus: {
        pending: 'Pending',
        paid: 'Paid',
        cooking: 'Cooking',
        out_for_delivery: 'On the Way',
        completed: 'Delivered',
      },
      steps: ['Placed', 'Paid', 'Cooking', 'On the Way', 'Delivered'],
    },
    bookingForm: {
      title: 'Reserve a Table',
      fields: {
        name: 'Your Name',
        email: 'Email Address',
        phone: 'Phone Number',
        date: 'Date',
        time: 'Time Slot',
        partySize: 'Guests',
        specialRequests: 'Special Requests',
      },
      placeholders: {
        name: 'John Doe',
        email: 'john@example.com',
        phone: '+254 712 345678',
        asks: 'Please mention any dietary requirements or table preferences.',
      },
      preferredTimeSlot: 'Preferred Time Slot',
      guest: 'Guest',
      guests: 'Guests',
      submit: 'Confirm Booking Request',
      successTitle: 'Reservation Requested!',
      successMessage: 'Thank you, {name}. We have received your booking request for {party_size} guests on {date} at {time}.',
      successNote: 'Note: All bookings are initial pending requests. Our host team will verify availability and confirm your reservation via email shortly.',
      successButton: 'Book Another Table',
      errorNoTime: 'Please select a time slot.',
      errorGeneral: 'An error occurred while booking. Please try again.',
    },
    menuItemCard: {
      available: 'Available',
      outOfStock: 'Out of Stock',
      add: 'Add',
    },
  },
  so: {
    language: {
      english: 'Ingiriisi',
      somali: 'Soomaali',
      englishShort: 'ENG',
      somaliShort: 'SOM',
      selectLanguage: 'Luqad',
      deepTranslate: 'Degdeg ahaan u badal Ingiriisi/Soomaali',
    },
    nav: {
      home: 'Guri',
      aboutUs: 'Nagu Saabsan',
      menu: 'Menu',
      orderOnline: 'Dalbo Online',
      reservations: 'Meeleynta',
      contact: 'Nala Soo Xiriir',
    },
    brand: {
      name: 'Sowda maqaayad',
      subtitle: 'Cunto Heer Sare ah',
    },
    userMenu: {
      adminDashboard: 'Dashboard Maamul',
      myProfileOrders: 'Xogta iyo Dalabka',
      logout: 'Ka Bax',
      login: 'Gali',
      userLogin: 'Gal Isticmaale',
      adminLogin: 'Gal Maamul',
      register: 'Diiwaan Geli',
      continueShopping: 'Sii Wad Iibsiga',
      remove: 'Ka saar',
      settings: 'Dejinta',
    },
    footer: {
      navigation: 'Hagitaan',
      openingHours: 'Waqtiga Furitaanka',
      contactUs: 'Nala Soo Xiriir',
      allRights: 'Dhammaan xuquuqaha way xifdameen. Waxaa loo nashqadeeyey si xarrago leh.',
      ourMenu: 'Menu-geena',
    },
    buttons: {
      bookTable: 'Booqo Miis',
      orderOnline: 'Dalbo Online',
      viewFullMenu: 'Eeg Menu-ga oo dhan',
      sendMessage: 'Dir Fariin',
      proceedToCheckout: 'Sii wad Bixinta',
      exploreMenu: 'Soo hel Menu-ga',
      placeFirstOrder: 'Samee Dalabkaaga Kowaad',
      registerAccount: 'Diiwaan Geli Akoon',
      loginSession: 'Gal',
      backToHome: 'Ku Laabo Guriga',
      reserveNow: 'Hadda Meel Booqo',
      sendAnotherMessage: 'Dir Fariin Kale',
      bookAnotherTable: 'Booqo Miis Kale',
      continueShopping: 'Sii Wad Iibsiga',
      trackOrder: 'Raadi Dalabka',
    },
    home: {
      heroBadge: 'Khibrad Cunto Sare leh',
      heroTitle: 'Meesha Cunto Sare iyo Raaxo Isku Milmaan',
      heroDescription: 'Ku soo dhawoow Sowda maqaayad. Dareenkaaga ku dhex noqo safar cunto oo raaxo leh oo ay dhiseen xirfadlayaal cunto Faransiis ah.',
      heroImageAlt: 'Aagga Cuntada ee Maqaayadda',
      heroCaption: 'Sowda maqaayad Main Salon',
      michelinText: '3 Michelin',
      organicText: '100% Organic',
      features: [
        {
          title: 'Cunto Kariyayaal Michelin',
          description: 'Jikadeenu waxaa hoggaamiya xirfadlayaal la abaalmariyey oo samaynaya cunto Faransiis dhiirigelisay.',
        },
        {
          title: 'Maaddooyin Organic Fudud',
          description: 'Cunto kasta waxaa maalin kasta laga diyaariyaa khudaar maxalli ah iyo hilib tayo sare leh.',
        },
        {
          title: 'Jawiga Qurxoon',
          description: 'Ku raaxayso cunto heer sare ah oo leh naqshad gaar ah, nalal qaali ah, iyo adeeg taxaddar leh.',
        },
      ],
      testimonials: [
        {
          name: 'Sophia Loren',
          role: 'Gourmet Critic',
          rating: 5,
          comment: 'Lobster Bisque-kan waa farshaxan. Dhadhanka iyo dhammaystirka jilicsan lama barbar dhigo.',
        },
        {
          name: 'Marcus Aurelius',
          role: 'Marti Joog Joogto ah',
          rating: 5,
          comment: 'Sowda maqaayad marna ma yaabin. Steak-kii Wagyu wuu dumi jiray sida subagga, adeeguna wuu fiicnaa.',
        },
        {
          name: 'Elena Rostova',
          role: 'Blogger Cunto',
          rating: 4.5,
          comment: "Naqshad cajaa'ib leh, faahfaahinta glassmorphism aad u qurux badan, iyo cunto si fiican u dhadhan leh.",
        },
      ],
      featuredTitle: 'Abuurista Muhiimka ah',
      experienceTitle: 'Cuntooyinka Oo Farshaxan Noqda',
      experienceDescription: 'Falsafadeenu waxay diiradda saareysaa dhadhanka nadiifka ah, fulinta saxda ah, iyo safar dareen ah.',
      reviewTag: 'Faallooyinka',
      reviewHeading: 'Maxay Cuntojireyaashu Yiraahdaan',
      ctaReserve: 'Hadda Meel Booqo',
      chefSelection: 'Doorashada Chef-ka',
      diningExperience: 'Khibradda Cuntada',
      starsExcellence: 'Xiddigaha Heer Sare',
      farmToTable: 'Ka Beerka Miiska',
    },
    about: {
      storyTag: 'Sheekadeena',
      heading: 'Sowda maqaayad',
      intro: 'La aasaasay 2012, Sowda maqaayad waxay isku darsatay dhaqanka cunto Faransiis iyo sayniska casriga ah ee cuntooyinka.',
      chefImageAlt: 'Chef-ka oo Diyaarinaya Cunto',
      heritageTag: 'Dhaxalka',
      heritageTitle: 'Ka Dhashay Jacaylka Cunto',
      heritageDescription1: 'Chef Antoine Laurent wuxuu maqaayadda furay si uu cunto heer sare ah uga dhigo mid la heli karo.',
      heritageDescription2: 'Waxay ku taallaa xarunta degmada taariikhiga ah, iyadoo isku daraysa dhismo qadiimi ah iyo raaxo casri ah.',
      metrics: [
        { title: 'Farsamooyin Run ah', description: 'Saabuun hoos u dhacdeeda, cajiin gacanta lagu qojiyo, iyo dubista digsi naxaas.' },
        { title: 'Hal-abuurnimo', description: 'Xakamaynta sous-vide ee tiknoolajiyada casriga ah iyo urta qiiqa cuntooyinka.' },
        { title: 'Daryeel 100%', description: 'Maaddooyinka maxalliga ah iyo taxadarka xasaasiyadda.' },
      ],
      teamTag: 'Xirfadlayaasha',
      teamTitle: 'La kulan Kooxdayada Cunto',
      team: [
        { name: 'Chef Antoine Laurent', role: 'Executive Chef & Founder', description: 'Paris ayuu ka tababbaray hoggaamiyeyaasha Michelin, Antoine-na 20 sano ayuu ku khibrad yeeshay.' },
        { name: 'Elena Rostova', role: 'Master Pastry Chef', description: 'Elena waxay abuurtaa macmacaanka farshaxanka leh ee isku dara dubista dhaqanka iyo qaabka casriga ah.' },
        { name: 'Jean-Pierre Dubois', role: 'Head Sommelier', description: 'Xulaha khamriga ee ugu fiican ee martida kasta la socda.' },
      ],
    },
    contact: {
      headerTag: 'Nala Soo Xiriir',
      heading: 'Waxaan Jeclaan Lahaa Inaan Ka Maqalno',
      description: "Su'aal ka qabta menu-ga, dhacdo gaar ah, ama karinta? Naga soo qor fariin, kooxda martida ayaa 24 saac gudaheed kaaga jawaabi doonta.",
      infoTitle: 'Macluumaad Xiriir',
      hoursTitle: 'Saacadaha Qolka Cuntada',
      locationLabel: 'Goobteena',
      hotlineLabel: 'Khadka Tooska ah',
      emailLabel: 'Cinwaanka Email-ka',
      formHeading: 'Noo Soo Dir Fariin',
      successHeading: 'Fariinta Waa La Diray!',
      successDescription: 'Waad ku mahadsan tahay in aad nala soo xiriirtay. Fariintaada si guul leh ayaa loo gudbiyey.',
      fields: { name: 'Magacaaga', email: 'Email-ka', subject: 'Mowduuca', message: 'Fariinta' },
      placeholders: {
        name: 'John Doe',
        email: 'john@example.com',
        subject: "Su'aal ku saabsan booska gaarka ah",
        message: "Qor faahfaahinta su'aashaada...",
      },
      mapLocation: '42 Champs-Élysées',
      mapCity: 'Paris, France 75008',
      mapHint: 'Muuqaal Khariidad Dhisme Ah',
      hours: [
        { label: 'Isniin - Jimce', value: '17:00 - 23:00' },
        { label: 'Sabti', value: '12:00 - 23:30' },
        { label: 'Axad', value: '12:00 - 22:00' },
      ],
      privateEventsTitle: 'Dhacdooyinka Gaarka ah & Xafladaha',
      privateEventsDescription: 'Waxaan martigelin karnaa casho gaar ah, soo dhawaysi shirkadeed, iyo aroosyo ilaa 80 qof.',
      privateEventsContact: 'La xidhiidh maamulaha dhacdooyinka si aad u hesho menu gaar ah.',
    },
    menu: {
      smallTitle: 'Le Menu',
      heading: 'Khibrad Menu-geena',
      placeholder: 'Raadi cuntooyinka gaarka ah...',
      defaultSorting: 'Kala soocid Caadi ah',
      priceLow: 'Qiimo: Hoos ilaa Sare',
      priceHigh: 'Qiimo: Sare ilaa Hoos',
      nameSort: 'Magac: A ilaa Z',
      allItems: 'Dhammaan Alaabada',
      noResultsTitle: 'Ma Jiraan Cuntooyin La Helay',
      noResultsDescription: 'Isbeddel raadintaada ama qaybsiga isku day.',
    },
    ordering: {
      smallTitle: 'Gaarsiinta Gourmet',
      heading: 'Dalbo Online',
      placeholder: 'Raadi cuntooyinka si aad boorsada ugu darto...',
      allItems: 'Dhammaan Alaabada',
      noItems: 'Alaab kama helin dookhyadaaga.',
      bagTitle: 'Boorsadaada Cuntada',
      emptyTitle: 'Boorsadaadu waa faaruq',
      emptySubtitle: 'Ku dar cuntooyin dhadhan leh liiska bidix si aad u bilowdo.',
      totalAmount: 'Wadarta Guud',
      freeDelivery: 'Bilaash',
      deliveryFee: 'Kharashka Gaarsiinta',
      checkoutButton: 'Sii wad Bixinta',
    },
    cart: {
      headerTag: 'Xulashooyinkaaga',
      heading: 'Gaadhista Iibsiga',
      orderSummary: 'Kooban Dalabka',
      dishDetailsHeader: 'Faahfaahinta Cuntada',
      priceHeader: 'Qiimaha',
      quantityHeader: 'Tirada',
      totalHeader: 'Wadarta',
      priceLabel: 'Qiime:',
      qtyLabel: 'Tirada:',
      totalLabel: 'Wadarta:',
      gourmetSubtotal: 'Wadarta Hore',
      estimatedTax: 'VAT Qiyaas ah (10%)',
      deliveryFee: 'Kharashka Gaarsiinta / Adeegga',
      complimentary: 'Bilaash',
      totalCost: 'Qiimaha Guud',
      emptyTitle: 'Gaadhigaagu waa Faaruq',
      emptyDescription: 'Waxay umuuqataa inaadan weli ku darin cuntooyinkaaga gaadhiga. Booqo menu-geena oo saham cuntooyinka.',
    },
    foodDetails: {
      back: 'Ku Laabo',
      dishNotFoundTitle: 'Cunto Lama Heli Karo',
      dishNotFoundBody: 'Alaabta aad raadineyso ma jirto ama waa la tirtiray.',
      backToMenu: 'Ku Laabo Menu-ga',
      keyIngredients: 'Waxyaabaha Muhiimka ah',
      nutritionInfo: 'Macluumaadka Nafaqada',
      addToCart: 'Ku dar Gaadhiga',
      addedToCart: 'Ku daray Gaadhiga!',
      outOfStock: 'Ma jiro',
      ingredients: [
        'Waxyaabaha deegaanka ah ee organic',
        'Dhameystir gaar ah oo guri lagu sameeyay',
        'Xawaash dhaqameed iyo subag isku darka',
        'Xawaash si taxaddar leh loo xushay',
      ],
      nutritionLabels: {
        calories: 'Kalooriyo',
        protein: 'Broteen',
        fat: 'Dufan',
        carbs: 'Karbohaydrayt',
      },
    },
    checkout: {
      headerTag: 'Dhammeystir Cuntada',
      heading: 'Bixinta Ammaan',
      deliveryDetails: '1. Faahfaahinta Gaarsiinta',
      recipientName: 'Magaca Qaataha',
      phoneNumber: 'Nambarka Taleefanka',
      orderType: 'Nooca Dalabka',
      homeDelivery: 'Gaarsiin Guriga',
      restaurantPickup: 'Qaado Maqaayadda',
      deliveryAddress: 'Cinwaanka Gaarsiinta',
      paymentDetails: '2. Habka Lacag-bixinta',
      creditCard: 'Kaarka Debit/Kredit',
      cashOnDelivery: 'Lacag Markay Gaadho',
      payAtCounter: 'Ka Bixi Kaantaroolka',
      cardNumber: 'Lambarka Kaarka',
      cardExpiry: 'Taariikhda Dhicitaanka',
      cardCvc: 'CVC Code',
      confirmOrder: 'Xaqiiji Dalabka',
      authorizingPayment: 'Lacag-bixinta kaarka waa la xaqiijinayaa...',
      orderConfirmed: 'Dalabka Waa La Xaqiijiyey!',
      orderThankYou: 'Waad ku mahadsan tahay inaad dooratay Sowda maqaayad. Dalabkaaga',
      orderThankYouSuffix: 'waa la helay waxaana hadda diyaarinayaa farsamayaqaannadayada.',
      orderSummary: 'Kooban Dalabka',
      orderStatus: 'Xaaladda Dalabka',
      preparationType: 'Nooca Diyaarinta',
      totalPaid: 'Wadarta La Bixiyey',
      modify: 'Wax Ka Beddel',
      trackOrder: 'Raadi Dalabka',
      backToHome: 'Ku Laabo Guriga',
      subtotal: 'Wadarta Hore',
      vat: 'VAT (10%)',
      grandTotal: 'Wadarta Guud',
    },
    reservations: {
      smallTitle: 'Meeleynta Cuntada',
      heading: 'Xiliga Miiska',
      description: 'Booqo miiskaaga Sowda maqaayad. Ku raaxayso cunto Faransiis heer sare ah iyo adeeg taxadar leh.',
      guidelinesTitle: 'Hagayaasha Meeleynta',
      guidelinesIntro: 'Si loo xaqiijiyo jawi raaxo leh, waxaan xaddidnaa xeerarka soo socda:',
      policies: [
        { title: 'Xeerka Labiska', description: 'Fadlan ka fogow dharka ciyaaraha, dharka xeebta, iyo funaanadaha caadiga ah.' },
        { title: 'Waqti iyo Qorshe', description: 'Miisaska waxaa la hayaa ugu badnaan 15 daqiiqo. Nala soo xiriir haddii aad dib u dhacdo.' },
        { title: 'Joojinta', description: 'Isbeddelka ama kansalinta waa in ugu yaraan 24 saac hor dhacdaa.' },
      ],
      privateEventsTitle: 'Dhacdooyinka Gaarka ah & Xafladaha',
      privateEventsDescription: 'Waxaan martigelin karnaa casho gaar ah, soo dhawaysi shirkadeed, iyo aroosyo ilaa 80 qof.',
      privateEventsContact: 'Email: events@sowda.com | Tel: +254 724 631727',
    },
    login: {
      heading: 'Gelitaanka Macmiilka',
      description: 'Gali si aad u dalbato cunto iyo aad u maamusho boosaskaaga.',
      emailLabel: 'Cinwaanka Email-ka',
      passwordLabel: 'Furaha Sirta',
      emailPlaceholder: 'john@example.com',
      passwordPlaceholder: '••••••••',
      loginButton: 'Gali',
      registerPrompt: 'Ma haysataa akoonto?',
      registerLink: 'Halkan Diiwaan Geli',
      adminPrompt: 'Ma tahay maamule?',
      adminLink: 'Isticmaal bogga galitaanka maamulaha',
      invalidCredentials: 'Email ama furaha sirta ayaa khaldan.',
    },
    adminLogin: {
      heading: 'Gelitaanka Maamulka',
      description: 'Gali si aad ugu gasho dashboard-ka Sowda adoo isticmaalaya aqoonsiga maamulaha.',
      adminEmailLabel: 'Email-ka Maamulka',
      passwordLabel: 'Furaha Sirta',
      emailPlaceholder: 'admin@sowda.com',
      passwordPlaceholder: '••••••••',
      loginButton: 'Gelitaanka Maamulka',
      invalidCredentials: 'Email ama furaha sirta ma saxna.',
      needCustomerAccount: 'Ma u baahan tahay akoonto macmiil?',
      userLogin: 'Gelitaanka Macmiilka',
      dontHaveAccount: 'Ma haysataa akoonto?',
      registerHere: 'Halkan Diiwaan Geli',
    },
    register: {
      heading: 'Abuur Akoon',
      description: 'Diiwaangeli si aad u dalbato cunto iyo u xajiso boosaska.',
      nameLabel: 'Magacaaga',
      emailLabel: 'Cinwaanka Email-ka',
      passwordLabel: 'Furaha Sirta',
      confirmPasswordLabel: 'Xaqiiji Furaha Sirta',
      placeholderName: 'John Doe',
      passwordPlaceholder: '••••••••',
      registerButton: 'Diiwaan Geli Akoon',
      existingAccountPrompt: 'Miyaad horey u leedahay akoonto?',
      loginLink: 'Halkan Gali',
      passwordMismatch: 'Furayaasha sirta ma isku mid yihiin.',
      registrationFailed: 'Diiwaangelintu way fashilantay. Fadlan isku day mar kale.',
    },
    profile: {
      headerTag: 'Akoontayda',
      heading: 'Profile & Taariikh',
      ordersTab: 'Dalabyada',
      reservationsTab: 'Boosaska',
      settingsTab: 'Dejinta',
      orderSectionTitle: 'Dalabka',
      orderedOn: 'Waxaa la dalbaday',
      totalPaid: 'Wadarta La Bixiyey',
      orderTracker: 'Raad Raac Dalabka',
      cancelledOrder: 'Dalabkan waa la kansalay.',
      noOrders: 'Taariikh dalab ma jirto.',
      placeFirstOrder: 'Samee Dalabkaaga Kowaad',
      noBookings: 'Boos ma jirto.',
      bookATable: 'Booqo Miis',
      roleLabel: 'Doorka',
      memberSince: 'Xubin tan iyo',
      settingsTitle: 'Dejinta Profile-ka',
      nameLabel: 'Magacaaga',
      emailLabel: 'Cinwaanka Email-ka',
      newPasswordLabel: 'Furaha Sirta Cusub (ikhtiyaari)',
      updatePasswordPlaceholder: 'Ha buuxin haddii aad rabto inaad sii haysato furahaaga hadda',
      savingChanges: 'Isbeddelada waa la kaydinayaa...',
      profileUpdated: 'Profile-ka si guul leh ayaa loo cusbooneysiiyey.',
      updateProfileButton: 'Kaydi Isbeddelada',
      profileError: 'Profile-ka ma cusbooneysiin.',
      settingsIntro: 'Cusboonaysii macluumaadkaaga iyo furaha sirta ee hoose.',
      liveOrderStatus: {
        pending: 'Sugaya',
        paid: 'La bixiyey',
        cooking: 'Karinta',
        out_for_delivery: 'Waddada',
        completed: 'La Keenay',
      },
      steps: ['La Dhigay', 'La Bixiyey', 'Karinta', 'Waddada', 'La Keenay'],
    },
    bookingForm: {
      title: 'Booqo Miis',
      fields: {
        name: 'Magacaaga',
        email: 'Email-ka',
        phone: 'Nambarka Taleefanka',
        date: 'Taariikh',
        time: 'Waqtiga',
        partySize: 'Martida',
        specialRequests: 'Codsiyada Gaarka ah',
      },
      placeholders: {
        name: 'John Doe',
        email: 'john@example.com',
        phone: '+254 712 345678',
        asks: 'Fadlan sheeg xasaasiyadaha ama doorashooyinka miiska.',
      },
      preferredTimeSlot: 'Waqtiga La Dooranayo',
      guest: 'Marti',
      guests: 'Martida',
      submit: 'Xaqiiji Dalabka',
      successTitle: 'Codsiga Meeleynta Waa La Helay!',
      successMessage: 'Mahadsanid, {name}. Waxaan helnay codsigaaga booska oo ah {party_size} qof oo taariikhdu tahay {date} saacadda {time}.',
      successNote: 'Ogeysiis: Booqooyinku waa codsiyo qarsoon oo kooxda martidu ay xaqiijin doonaan oo email kuugu soo diri doonaan.',
      successButton: 'Booqo Miis Kale',
      errorNoTime: 'Fadlan dooro waqtiga.',
      errorGeneral: 'Waxaa dhacay qalad. Fadlan isku day mar kale.',
    },
    menuItemCard: {
      available: 'La heli karo',
      outOfStock: 'Maa jira',
      add: 'Kudar',
    },
  },
};

const LanguageContext = createContext({
  language: 'en',
  setLanguage: () => {},
  t: () => '',
});

const getTranslation = (language, path, fallback = '') => {
  if (!path) return fallback;
  const value = path.split('.').reduce((obj, key) => (obj && obj[key] !== undefined ? obj[key] : undefined), translations[language]);
  return value !== undefined ? value : fallback;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    const localLang = localStorage.getItem(LANGUAGE_STORAGE_KEY);
    if (localLang === 'so' || localLang === 'en') {
      setLanguage(localLang);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
  }, [language]);

  const t = (path, fallback = '') => getTranslation(language, path, fallback);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
